"""Output formatters for AWS Bill Whisperer."""

from datetime import datetime
from typing import Any


def to_markdown(analysis: str, cost_data: dict) -> str:
    """
    Format analysis as pretty markdown.

    Args:
        analysis: LLM-generated analysis text
        cost_data: Cost data from get_full_analysis()

    Returns:
        Formatted markdown string
    """
    usage = cost_data.get('usage', {})
    comparison = cost_data.get('comparison', {})

    lines = []

    # Header
    lines.append("# 📊 AWS Bill Whisperer Analysis")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")

    # Summary box
    lines.append("---")
    period = usage.get('period', {})
    lines.append(f"**Period:** {period.get('start', 'N/A')} to {period.get('end', 'N/A')}")
    lines.append(f"**Total Cost:** ${usage.get('total', 0):,.2f}")

    if comparison:
        change = comparison.get('change', 0)
        change_pct = comparison.get('change_percent', 0)
        direction = "📈" if change > 0 else "📉" if change < 0 else "➡️"
        lines.append(f"**vs Previous Period:** {direction} ${change:+,.2f} ({change_pct:+.1f}%)")

    lines.append("---\n")

    # Top services table
    services = usage.get('services', [])[:10]
    if services:
        lines.append("## 💰 Top Services\n")
        lines.append("| Service | Cost | % of Total |")
        lines.append("|---------|-----:|:----------:|")
        for svc in services:
            lines.append(f"| {svc['name']} | ${svc['cost']:,.2f} | {svc['percent']}% |")
        lines.append("")

    # Service changes (if comparison available)
    if comparison and comparison.get('service_changes'):
        lines.append("## 🔄 Biggest Changes\n")
        lines.append("| Service | Previous | Current | Change |")
        lines.append("|---------|----------|---------|-------:|")
        for svc in comparison['service_changes'][:5]:
            emoji = "🔺" if svc['change'] > 0 else "🔻"
            lines.append(
                f"| {svc['name'][:40]} | ${svc['previous']:,.2f} | ${svc['current']:,.2f} | "
                f"{emoji} {svc['change_percent']:+.1f}% |"
            )
        lines.append("")

    # LLM Analysis
    lines.append("## 🤖 AI Analysis\n")
    lines.append(analysis)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by [AWS Bill Whisperer](https://github.com/hamley241/aws-bill-whisperer)*")

    return "\n".join(lines)


def to_slack(analysis: str, cost_data: dict) -> dict:
    """
    Format analysis as Slack blocks.

    Args:
        analysis: LLM-generated analysis text
        cost_data: Cost data from get_full_analysis()

    Returns:
        Slack message payload with blocks
    """
    usage = cost_data.get('usage', {})
    comparison = cost_data.get('comparison', {})

    blocks = []

    # Header
    blocks.append({
        "type": "header",
        "text": {"type": "plain_text", "text": "📊 AWS Cost Analysis", "emoji": True}
    })

    # Summary
    period = usage.get('period', {})
    summary_text = f"*Period:* {period.get('start', 'N/A')} to {period.get('end', 'N/A')}\n"
    summary_text += f"*Total:* ${usage.get('total', 0):,.2f}"

    if comparison:
        change = comparison.get('change', 0)
        change_pct = comparison.get('change_percent', 0)
        emoji = "📈" if change > 0 else "📉" if change < 0 else "➡️"
        summary_text += f"\n*vs Previous:* {emoji} ${change:+,.2f} ({change_pct:+.1f}%)"

    blocks.append({
        "type": "section",
        "text": {"type": "mrkdwn", "text": summary_text}
    })

    blocks.append({"type": "divider"})

    # Top 5 services
    services = usage.get('services', [])[:5]
    if services:
        service_text = "*Top Services:*\n"
        for svc in services:
            service_text += f"• {svc['name']}: ${svc['cost']:,.2f} ({svc['percent']}%)\n"

        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": service_text}
        })

    blocks.append({"type": "divider"})

    # Analysis (truncate for Slack's 3000 char limit per block)
    analysis_truncated = analysis[:2900] + "..." if len(analysis) > 2900 else analysis
    blocks.append({
        "type": "section",
        "text": {"type": "mrkdwn", "text": f"*Analysis:*\n{analysis_truncated}"}
    })

    # Footer
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated {timestamp} by AWS Bill Whisperer"}
        ]
    })

    return {"blocks": blocks}


def to_json(analysis: str, cost_data: dict) -> dict[str, Any]:
    """
    Return structured JSON output.

    Args:
        analysis: LLM-generated analysis text
        cost_data: Cost data from get_full_analysis()

    Returns:
        Structured dict ready for JSON serialization
    """
    return {
        "generated_at": datetime.now().isoformat(),
        "analysis": analysis,
        "summary": {
            "total": cost_data.get('usage', {}).get('total', 0),
            "period": cost_data.get('usage', {}).get('period', {}),
            "change_percent": cost_data.get('comparison', {}).get('change_percent', 0),
        },
        "cost_data": cost_data
    }
